import { StyleSheet } from 'react-native';
import { Theme } from '../../../../../context/ThemeContext';

export const createWeeklyCalendarStyles = (theme: Theme) => StyleSheet.create({
  weeklyCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 20,
    marginBottom: 24,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  weeklyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  weeklyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.text,
  },
  weeklyProgress: {
    fontSize: 14,
    color: theme.textSecondary,
  },
  weeklyCalendar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
  },
  calendarDay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 6,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: theme.border,
    backgroundColor: theme.surface,
    position: 'relative',
    minHeight: 110,
  },
  calendarDayClaimed: {
    borderColor: theme.success,
    backgroundColor: `${theme.success}10`,
  },
  calendarDayToday: {
    borderColor: theme.primary,
    backgroundColor: theme.primaryLight,
    shadowColor: theme.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  calendarDaySpecial: {
    borderColor: theme.warning,
    backgroundColor: `${theme.warning}10`,
  },
  specialBadge: {
    position: 'absolute',
    top: -1,
    right: -1,
    width: 16,
    height: 16,
    backgroundColor: theme.warning,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarDayIcon: {
    padding: 6,
    borderRadius: 10,
    backgroundColor: theme.border,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
  },
  calendarDayIconClaimed: {
    backgroundColor: `${theme.success}20`,
  },
  calendarDayIconToday: {
    backgroundColor: theme.primaryLight,
  },
  calendarDayNumber: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.text,
    marginBottom: 6,
    textAlign: 'center',
  },
  calendarDayReward: {
    fontSize: 9,
    color: theme.textSecondary,
    textAlign: 'center',
    lineHeight: 12,
    paddingHorizontal: 1,
    numberOfLines: 2,
  },
  claimedDot: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.success,
  },
  todayPulse: {
    position: 'absolute',
    top: -2,
    left: '50%',
    marginLeft: -4,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.primary,
  },
});